### PR TITLE
Change damage way handle

### LINKED ISSUE #326: Unintended consequences from the way damage is handled
**Describe the bug**
When using an item, the amount of damage that is done should be a factor in how much durability is taken from the axe, and all tiles should be changed so that the damage of the tile makes sense. Currently ore tiles are given very little health, and other tree tiles are given more, yet the damage done is widely different. The damage applied should be the same for every tile for the same tool, with the addition of some randomness on top.

**Additional context**
Bug to fix before release

### LINKED ISSUE #328: Popup menu overflows (in both 4x3 and 16x9)
**Describe the bug**
A number of popup menus overflow off the edges of the screen. This list will be updated with my findings.

**To Reproduce**
- Reset key binds

**Expected behavior**
No overflow of popup menus.

**Screenshots**
RESET KEYBINDS:
(4x3)
Screen Shot 2022-04-26 at 5 07 35 PM
(16x9)
Screen Shot 2022-04-26 at 4 57 26 PM

### PR DESCRIPTION
**Pull request by BenCheung0422**
Fixes #326 
Fixes #328

### CODE REVIEW

File: src/main/java/minicraft/level/tile/HardRockTile.java [hunk 1]
```diff
@@ -41,8 +41,9 @@ public boolean interact(Level level, int xt, int yt, Player player, Item item, D
 		if (item instanceof ToolItem) {
 			ToolItem tool = (ToolItem) item;
 			if (tool.type == ToolType.Pickaxe && tool.level == 4) {
-				if (player.payStamina(4 - tool.level) && tool.payDurability()) {
-					hurt(level, xt, yt, random.nextInt(10) + (tool.level) * 5 + 10);
+				int dmg = random.nextInt(10) + tool.damage;
```
Comment (Makkkkus) [inline src/main/java/minicraft/level/tile/HardRockTile.java:44]: tool.damage should be a private variable, and getters should be replaced with tool.getDamage() which includes randomness with a bound of 5.

File: src/main/java/minicraft/level/tile/OreTile.java [hunk 2]
```diff
@@ -82,7 +83,7 @@ public Item getOre() {
     
 	public void hurt(Level level, int x, int y, int dmg) {
 		int damage = level.getData(x, y) + dmg;
-		int oreH = random.nextInt(10) + 3;
+		int oreH = random.nextInt(10)*4 + 20;
```
Comment (Makkkkus) [inline src/main/java/minicraft/level/tile/OreTile.java:86]: Formatting

**Review by Makkkkus — CHANGES_REQUESTED** [review]
You implemented this by forgetting the most important part of the issue. Namely, changing how much damage tiles can take.

File: src/main/java/minicraft/core/Game.java [hunk 3]
```diff
@@ -105,24 +105,26 @@ public static void main(String[] args) {
...
 		Tiles.initTileList();
 		Sound.init();
 
 		World.resetGame(); // "half"-starts a new game, to set up initial variables
 		player.eid = 0;
 		new Load(true); // This loads any saved preferences.
+		MAX_FPS = (int) Settings.get("fps");
 
-    Localization.loadLanguage();
+		Localization.changeLanguage((String)Settings.get("language"));
```
Comment (Makkkkus) [inline src/main/java/minicraft/core/Game.java:123]: Why did you add this? Please remove it.

File: src/main/java/minicraft/item/ToolItem.java [hunk 4]
```diff
@@ -66,29 +68,32 @@ public boolean isDepleted() {
...
 	}
-	
+
 	public boolean payDurability() {
 		if (dur <= 0) return false;
 		if (!Game.isMode("creative")) dur--;
 		return true;
 	}
+
+	public int getDamage() {
```
Comment (Makkkkus) [inline src/main/java/minicraft/item/ToolItem.java:78]: Good!

File: src/main/java/minicraft/core/Game.java (hunk 3 above)
Comment (BenChueng0422) [reply src/main/java/minicraft/core/Game.java:123]: I think this resolved that these settings are not being applied in setup.

Comment (Makkkkus) [reply src/main/java/minicraft/core/Game.java:123]: No, I have already fixed that. Take a look at the line below.

Comment (BenChueng0422) [reply src/main/java/minicraft/core/Game.java:123]: But I haven't seen that Localization.loadLocalizatiom get from settings.

Comment (Makkkkus) [reply src/main/java/minicraft/core/Game.java:123]: Okay, good

Comment (BenChueng0422) [reply src/main/java/minicraft/core/Game.java:123]: Done.

**Comment by BenChueng0422** [comment]
I also noticed that the popup menus don't get localizations.

**Comment by Makkkkus** [comment]
Don't put bloat into pull requests. Keep them clear and concise.

**Comment by BenCheung0422** [comment]
it's clear. I still cannot see @Litorom's reviews.

File: src/main/resources/resources/localization/english_en-us.json [hunk 5]
```diff
@@ -233,7 +233,7 @@
   "Controls": "Controls",
   "Press the desired": "Press the desired",
   "key sequence": "key sequence",
-  "Are you sure you want to reset all key bindings to the default keys?": "Are you sure you want to reset all key bindings to the default keys?",
+  "Are you sure you want to reset\nall key bindings\nto the default keys?": "Are you sure you want to reset\nall key bindings\nto the default keys?",
```
[the remark this answers is not in the document]
Comment (Litorom) [reply src/main/resources/resources/localization/english_en-us.json:236]: Idk why I had to submit a review for my post to show up.

[the remark this answers is not in the document]
Comment (BenCheung0422) [reply src/main/resources/resources/localization/english_en-us.json:236]: I think we need to change the localization ids for better compatibility for entries.

[the remark this answers is not in the document]
Comment (Litorom) [reply src/main/resources/resources/localization/english_en-us.json:236]: Yes that’s true. Thinking about it we cannot use escape keys in the locale files. It would be too confusing for those who will translate.

File: src/main/resources/resources/localization/english_en-us.json [hunk 6]
```diff
@@ -233,9 +233,9 @@
   "Controls": "Controls",
   "Press the desired": "Press the desired",
   "key sequence": "key sequence",
-  "Confirm setting key bindings.1": "Are you sure you want to reset",
-  "Confirm setting key bindings.2": "all key bindings",
-  "Confirm setting key bindings.3": "to the default keys?",
+  "Confirm resetting key bindings.1": "Are you sure you want to reset",
```
Comment (Litorom) [inline src/main/resources/resources/localization/english_en-us.json:236]: Like what @Makkkkus said on Discord, I suggest changing it to “minicraft.popup.reset_keybinds.1” as an example of what I would do.

**Review by Litorom — CHANGES_REQUESTED** [review]

File: .vscode/settings.json [hunk 7]
```diff
@@ -0,0 +1,10 @@
+{
```
Comment (Makkkkus) [inline .vscode/settings.json:1]: Delete this file please

File: src/main/java/minicraft/core/io/Localization.java [hunk 8]
```diff
@@ -133,7 +133,7 @@ public static void changeLanguage(@NotNull String newLanguage) {
 	 * This method gets the currently selected locale and loads it if it exists. If not, it loads the default locale.
 	 * The loaded file is then parsed, and all the entries are added to a hashmap.
 	 */
-	public static void loadLanguage() {
+	private static void loadLanguage() {
```
Comment (Makkkkus) [inline src/main/java/minicraft/core/io/Localization.java:136]: Good

File: src/main/java/minicraft/screen/KeyInputDisplay.java [hunk 9]
```diff
@@ -10,48 +13,48 @@
...
-			
+
 			popupBuilder
 				.setEntries(StringEntry.useLines(Color.YELLOW, "Press the desired", "key sequence"))
 				.createMenu(),
-			
+
 			popupBuilder
-				.setEntries(StringEntry.useLines(Color.RED, "Are you sure you want to reset all key bindings to the default keys?", "enter to confirm", "escape to cancel"))
+				.setEntries(StringEntry.useLines(Color.RED, "Confirm resetting key bindings.1", "Confirm resetting key bindings.2", "Confirm resetting key bindings.3", "enter to confirm", "escape to cancel"))
```
Comment (Makkkkus) [inline src/main/java/minicraft/screen/KeyInputDisplay.java:49]: The loc key for this should be `minicraft.display.key_input.confirm_popup`, and there should only be one entry.

File: src/main/java/minicraft/screen/entry/StringEntry.java [hunk 10]
```diff
@@ -21,29 +22,29 @@ public static StringEntry[] useLines(int color, String... lines) {
...
 	}
-	
+
 	public StringEntry(String text) {
 		this(text, DEFAULT_COLOR);
 	}
 	public StringEntry(String text, int color) {
 		setSelectable(false);
-		this.text = text;
+		this.text = Localization.getLocalized(text);
```
Comment (Makkkkus) [inline src/main/java/minicraft/screen/entry/StringEntry.java:34]: Change this to only localize if you explicitly tell it to. Take a look at how it is done in SelectEntry, and replicate that.

This also gives me an idea where we completely remove text, and replace it with an abstract string in the ListEntry class that represents the id of the entry, or maybe a total overhaul of the gui system, but that is for later.

**Review by Makkkkus — CHANGES_REQUESTED** [review]

File: src/main/java/minicraft/screen/KeyInputDisplay.java (hunk 9 above)
Comment (BenCheung0422) [reply src/main/java/minicraft/screen/KeyInputDisplay.java:49]: We need to separate it for line breaking.

File: src/main/java/minicraft/screen/entry/StringEntry.java (hunk 10 above)
Comment (BenCheung0422) [reply src/main/java/minicraft/screen/entry/StringEntry.java]: That would be in #313

File: src/main/resources/resources/localization/english_en-us.json [hunk 11]
```diff
@@ -233,11 +233,9 @@
   "Controls": "Controls",
   "Press the desired": "Press the desired",
   "key sequence": "key sequence",
-  "Confirm resetting key bindings.1": "Are you sure you want to reset",
-  "Confirm resetting key bindings.2": "all key bindings",
-  "Confirm resetting key bindings.3": "to the default keys?",
-  "enter to confirm": "enter to confirm",
-  "escape to cancel": "escape to cancel",
+  "minicraft.display.key_input.confirm_popup": "Are you sure you want to reset all key bindings to the default keys?",
+  "minicraft.display.keys_desc.enter_confirm": "enter to confirm",
```
Comment (Makkkkus) [inline src/main/resources/resources/localization/english_en-us.json:237]: I would replace keys_desc with popup
